sudo: required
services:
  - docker

before_install:
  - docker build -t fernansp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fernansp/react-test npm run test

after_succes:
  - docker build -t fersab89/multi-client ./client
  - docker build -t fersab89/multi-nginx ./nginx
  - docker build -t fersab89/multi-server ./server
  - docker build -t fersab89/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push fersab89/multi-client
  - docker push fersab89/multi-nginx
  - docker push fersab89/multi-server
  - docker push fersab89/multi-worker